cd base
del /s /q "sounds\music\[AOV] anime 2.mp3"
rmdir /s /q "characters\HajimeHinata"
ren "characters\Archibald Cronin (Doctor)" "Archibald Doctor"
ren "characters\Archibald Cronin (Casual)" "Archibald"
ren "characters\Connor O'Neal" "Connor"
ren "characters\Dmitri Demiglavski" "Dmitri"
ren "characters\Donnabella Bracknell" "Donnabella"
ren "characters\Grimesby Roylott" "Roylott"
ren "characters\Hart Vortex" "Vortex"
ren "characters\Mae Chambers" "Mae"
ren "characters\Matilda Roedall (Typewriter)" "Matilda"
ren "characters\Matilda Roedall (Headphones)" "Matilda Headset"
ren "characters\Narcissus Blacke" "Narcissus"
ren "characters\William Petenshy" "William"
ren "characters\Decago Mieterman" "Decago"