cd base
rmdir /s /q "background\OCBasement"
ren "evidence\AoJtape1" "AAItape"
ren "evidence\AAmissle2" "AAmissile2"
ren "evidence\DDCaseCandice" "DDCastCandice"
rmdir /s /q "characters\TobiasGregson"
rmdir /s /q "characters\Vortex"
rmdir /s /q "characters\Barnham\emotions"
rmdir /s /q "characters\Blackquill\emotions"
rmdir /s /q "characters\Dhurke\emotions"
rmdir /s /q "characters\Inquisitor Layton\emotions"
rmdir /s /q "characters\Rayfa\emotions"
rmdir /s /q "characters\Roger Retinz\emotions"
rmdir /s /q "characters\Ryu Leg\emotions"